language: java

jdk: oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - docker
  - mysql

before_install:
  - docker-compose --file docker-compose-travis.yml up -d
  
script:
  - mvn clean verify -B
