language: java

jdk: oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - docker
  - mysql

before_install:
  - echo "Skipping pre-install" # docker-compose --file docker-compose-travis.yml up -d
  - docker login -u="BINTRAY_USERNAME" -p="BINTRAY_API_KEY" appdirect-opensource-docker-docker.bintray.io
  
script:
  - echo "Skipping build for a test"

after_script:
  - mvn clean package docker:build -DpushImageTag # --settings settings.xml -X
