language: java

jdk: oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - docker
  - mysql

before_install:
  - docker-compose --file docker-compose-travis.yml up -d
  
script:
  - echo "Skipping build for a test"

after_script:
  - docker login -u ${BINTRAY_USERNAME} -p ${BINTRAY_API_KEY} -e open-source@appdirect.com appdirect-opensource-docker-docker.bintray.io
  - mvn clean package docker:build -DpushImageTag --settings settings.xml -X
