chatty.pie.host: https://operating-attic-146121.appspot.com
chatroom.report.subscriber: chatty.pie.team@yopmail.com
spring.datasource:
    #See http://stackoverflow.com/questions/7605953/how-to-change-mysql-timezone-in-java-connection for explanation 
    #on the `useLegacyDatetimeCode` parameter
    url: jdbc:mysql://localhost/chatty_pie_connector?useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: password

spring.mail:
    host: localhost
    port: 3025
