signature.validation.use.https: true
spring.mail:
    host: smtp.sendgrid.net
    port: 465
    properties:
      mail.smtp.ssl.enable: true
      mail.smtp.timeout: 5000
      mail.smtp.connectiontimeout: 5000
