chatty.pie.host: https://operating-attic-146121.appspot.com
spring.datasource:
    url: jdbc:mysql://localhost/chatty_pie_connector?createDatabaseIfNotExist=true
    username: root
    password: password
